version: '3.8'
services:
  filebrowser:
    networks:
      - traefik-public
    image: filebrowser/filebrowser
    volumes:
      - srv:/srv
      - db:/db
    configs:
      - source: filebrowser
        target: /.filebrowser.json
    deploy:
      placement:
        constraints:
          - node.labels.filebrowser.filebrowser-data == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.filebrowser-http.rule=Host(`${DOMAIN?ERROR}`)
        - traefik.http.routers.filebrowser-http.entrypoints=http
        - traefik.http.routers.filebrowser-http.middlewares=https-redirect
        - traefik.http.routers.filebrowser-https.rule=Host(`${DOMAIN?ERROR}`)
        - traefik.http.routers.filebrowser-https.entrypoints=https
        - traefik.http.routers.filebrowser-https.tls=true
        - traefik.http.routers.filebrowser-https.tls.certresolver=le
        - traefik.http.services.filebrowser.loadbalancer.server.port=80

configs:
  filebrowser:
    file: ./config.json

volumes:
  srv:
  db:

networks:
  traefik-public:
    external: true
